### ISSUE TITLE
Implement Map Store data  (Applicative)

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#106]
**Description:**
will include imagery data (map settings, etc) in a store that will make it available for consumers
 
- [ ] add new package for map store (@ansyn/map-facade) 
- [ ] add new Action for moveEnd
- [ ] update selectedCase with mapPosition
