### ISSUE TITLE
As a <User>, I want to <open multiple imagery views>, so that < I can have reference for analyzed data>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#122]
Open multiple imagery views, each display its own map with its own overlay.

- [x] Button to change the view to show to imagery views. (See design on drive) #140
- [x] Highlight active map borders.#140
- [x] Create status bar for each map. (See design on drive) #140

**Note:** In the end of the implementation  will be 4 imagery views.
The implementation should affected from this.

**Comment by eldadcohen1** [comment]
You can consulting with Yonatan about it

**Comment by carmelorr** [comment]
Please see new icons-
https://www.figma.com/file/OpHMLQ4eNnYWlv1lM0A2793w/Colombus-draft

@eldadcohen1 @idanbarak

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/27797606-f8d76588-6016-11e7-9d45-1e9c800d80b5.png)

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/27797829-b5602870-6017-11e7-8019-8fd2d6073b4e.png)
