### ISSUE TITLE
Launch application in context - As a <User> I want to <save application state in the url>, so that <I can launch the application in any state that I want> 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#197]
**_Set a meeting with @idanbarak and define the parameters for the url_**

- [x] define with @idanbarak all the parameters for application will be launching.  
                        _**write here all the conclusions as a comment**_
- [x] Save app state in the url  (routing ) according to @idanbarak 's definitions. #261
- [x] Launch the application according the url parameters #276
- [x] Button that generate the url (from case state). @idanbarak  #275
- [x] Unitest and doc. #276

**Comment by carmelorr** [comment]
last week we decided that the URL will include a basic format of:

URL- Region:  / time:   / metadata

Region will include all the geo filters in a wkt format
Time will include all the time filters in a start & end format.

**Comment by carmelorr** [comment]
Button that generate the url (from case state)-

two ways-
1. "share link" button in the case menu
2."share link" icon by hovering the "new case" in the status bar

**Comment by carmelorr** [comment]
![0 19](https://user-images.githubusercontent.com/26301386/27275837-ceda857a-54e1-11e7-99b8-7108fe2e5acd.png)

**Comment by carmelorr** [comment]
@eldadcohen1 @yairtawil 

update-

URL- Region: / time: /**context**: / metadata

context will include the following options: 

"surface peeling"
"how the surface looks now"
"launch by entity"
structure characterization
scan
pirs
