### ISSUE TITLE
Facets - As a<User>, I want to <filter overlays by overlays parameters> so that <I can see just the relevant overlay that I want to analyzed>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#198]
- [x]  Get all the requirement from @idanbarak #202
        **Please** : Write here the conclusions as a comment.
- [x] Design of facets + design review #211
- [x] Create facets component with UI #204 
- [x] Connect facets actions with overlays actions through app #205
- [x] Implement filtering process #206

Just facets that are has available values will be shown.
Overlay will be filtered by the facets. Just the filtered overlays will be shown on the timeline.
Unitest and design.

**Comment by MarkShleifer** [comment]
Overlay data model:

	id: string,
	footprint?: any,//@todo add type geojson_multipoligon,
	sensorType?: string,
	sensorName?: string,
	channel?: string,
	bestResolution?: number,
	isStereo?: boolean,
	name: string,
	imageUrl?: string,
	thumbnailUrl?: string,
	photoTime: Date,
	azimuth: number, //radians
	aproximateTransform?: any,
	csmState?: string,
	sourceType?:string

**Comment by carmelorr** [comment]
favorites- show only favorites (if checked show only)

**Comment by carmelorr** [comment]
please note, that the amount of active facets should appear as a "badge" indication on the side-bar icon.#211 
![image](https://user-images.githubusercontent.com/26301386/27547839-dda42d72-5a9f-11e7-9c93-c352dcb7c730.png)
