### ISSUE TITLE
As a <User>, I want to <navigate in the timeline> so that <I can select overlays to analayze> 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#22]
In the end of this user story the user should be able to do the following:

- [ ]  See the time line in his main view of AnSyn app.
- [ ]  See all the overlays between the date range.
- [ ] Selected specific overlay and save this state.

sub-tasks
- [x] #15

**Comment by osadan** [comment]
@eldadcohen1 by overlay you mean thumbnail ? 
I think it deserve an issue of it's own

**Comment by osadan** [comment]
I removed the #9 from the task list since it is not required
