### ISSUE TITLE
As a <User>, I want to <Get,Create, Update and Delete cases> so that <I can manage the context of the application> 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#23]
In the end of this user story the user will be able to do the following:
 
- [x] Get cases via scrolling (#28)
- [x] Create new case. (#38)
- [x] Update existing case. (#58)
- [x] Delete existing case. (#58)

- [x] The ability to select any case and to get its state.

Reminder: **The case mast save the context of the application snapshot**

**Comment by MarkShleifer** [comment]
Move to iteration 4
