### ISSUE TITLE
As a <public user>, I want to <insert url> so that <i can use the app from any location>.

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#237]
- **UserStory**

**Tasks**
- [x] Update mock data token logic
- [x] Create docker for mock data (includes db)
- [x] Create docker for ansyn app
- [x] Deploy on cloud

**Comment by yairtawil** [comment]
Done!
thanks to @eldadcohen1 the king!
