### ISSUE TITLE
As a <user developer>, I want to <save the state and the context of the application> so that <I can restore and understand the application state overall the app>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#24]
At the end of this user story we will achive the following:

- [ ] We will have a central store.
- [x] We will have a decision on wich store we are going to use. 
- [ ]  All the services and the component will get the data from the central store and will notify it.

**From this store we will mange the application state**

**Comment by MarkShleifer** [comment]
We have chosen ngrx and it will be combined in iteration 4
