### ISSUE TITLE
As a <user>, I want to <have status bar> so that <app state will be reflected to me>.

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#243]
- **user story**

**tasks**
- [ ] overlay description (1-4 imageries)
- [x] imagery view state (world, overlay, plugin defined.)
- [x] selected case
- [x] orientation (hard coded)
- [x] search overlays type (only pin-point)
- [x] timeline state (currently hard coded)
- [x] select layout as in wireframes file
- [x] number of overlays

@idanbarak needs to provide all relevant icons
