### ISSUE TITLE
As a <user>, I want to <search overlays by pin-point> so that <i can get all overlays that contains that point>.

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#245]
- **user story**

**tasks**
- [x] @idanbarak should define how the user selects a new pin-point for the case
- [ ] case state will save the pinpointed location as a region
- [ ] overlays will be searched according to the pinpointed location

**Comment by carmelorr** [comment]
edit geo filters and show/hide them

![image](https://user-images.githubusercontent.com/26301386/27120419-260a90aa-50ec-11e7-901b-60d93fbadd0b.png)
