### ISSUE TITLE
As a  <user developer>, I want to <have a package of imagery module>  so that <I combine it in any app>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#25]
At the end of this user story we will have the following:

- [ ] npm that can be installed and intergate in the AnSyn app.
- [ ] Modulare package that we can combine just what we want.

- [ ] Divide and pack ImageryView module only for OpenLayers #48

## _Note_: **Please divide the current imagery view to modules and explain the division on readMe file**

**Comment by MarkShleifer** [comment]
Move to iteration 4
