### ISSUE TITLE
As a <developer> , I want to <get relevant data for cases> so that <I can test the components and services that I develop>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#27]
In the end of this user story we will have the following:

- [x] Mock services for cases apis.
- [ ] All the apis will return relevant data
- [ ] After integration for the userstory #23

**Comment by MarkShleifer** [comment]
Move to iteration 4
