### ISSUE TITLE
Select data layer

### ISSUE THREAD

**Issue by MarkShleifer** [AnSyn/ansyn#30]
- [x] select father node and propagate to selection to its children
- [x] enable partial child selection and indeterminate checkbox state
- [x] write tests to layer-tree.component
- [x] write tests to layer-manager.component
- [x] C.R + merge to master

**Comment by MarkShleifer** [comment]
Move to iteration 4
