### ISSUE TITLE
As a <User>, I want to <be able to manipulate the pixels in the images> so that <I can enhance the presented image>  

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#320]
- [x] Integrate master branch of OpenLayers in Ansyn until NPM version is published #390
- [ ] Implement Histogram Equalization in Ansyn #405
- [ ] Tests and CR: Outside #326
- [ ] Integrate histogram equalization inside #406
- [ ] Test and CR: Inside #407
