### ISSUE TITLE
Data Source Provider - As a <developer>, I want to < develop mechanism to connect other overlays data sources> so that <our app will display overlays from multi source> 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#379]
- [x] Implement base class for overlay data source provider #393
- [ ] Extend the base class for Idaho overlay source provider and for G source provider #394 #413
- [x] Change the fetch overlays to work with the new mechanism. #396
- [x] Write unit tests
