### ISSUE TITLE
Context Menu - As a <User> I want to <be able to navigate the next,prev and best overlay with context menu from the map> so that <it will be easier for me to find the relevant overlay in specific point> 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#437]
- [x] Implement hit test in the map. #462
- [x] Implement open context menu from the map. #462
- [ ] Implement the logic for get next,prev,best resolution #474

Work closely with @idanbarak and @carmelorr
