### ISSUE TITLE
As a <User>, I want to <launch a case in his last state> so that <I can continue analyze from the same state>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#46]
In the end of this user story we will have the following:

- [ ] Restore case data from the server.
- [ ] Store the data in the central store.
- [ ] Get data from central store.
- [ ] Design + Architecture  
- [x] Integrate case module with store module that base on ngrx #45

**Comment by yairtawil** [comment]
what is case state? 
case state is built from all minimal data that can restore the view to his last presentation.
case state should include: 
- map state 
- facets state
- timeline state
- layer manager state

etc..
