### ISSUE TITLE
Imagery/Overlays - As a <User> , I want to <be able to select footprint from the map and see the overlay>, so that < I can get the exact overlay that I want to analyze>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#477]
- [ ] Implement Hit Test from the map (the selection should be jus on the outlines) #501 
- [x] Implement polyline visualizer #513
- [ ] Integrate the selection with the central store and update the case #501 
- [ ] Unittest #501  #513

@idanbarak @carmelorr Please add the relevant design issue for this User Story.

**Comment by carmelorr** [comment]
Please see design in #473

**Comment by idanbarak** [comment]
all design issues were given to @yairtawil
