### ISSUE TITLE
Divide and pack ImageryView module only for OpenLayers

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#48]
In the end of this user story we will have the following:

- [x] Architecture design for the sub modules.
- [ ] Divided to modules
- [x] Node package for this module

**Comment by eldadcohen1** [comment]
Moved for iteration 4 stretch

**Comment by eldadcohen1** [comment]
@asafMasa Please open task per module that you going to develope.
Give pricing for eatch task.
