### ISSUE TITLE
Timeline points inside of a range

### ISSUE THREAD

**Issue by osadan** [AnSyn/ansyn#7]
Create an api to get all the points inside the current range

**Comment by eldadcohen1** [comment]
@osadan this is still open?

**Comment by eldadcohen1** [comment]
#21

**Comment by osadan** [comment]
- [ ] try to move the function that inside labels.js (event drops) to the onzoomend 
- [ ] try to update also the dates in the extranum 
- [ ] try to chain some action in zoom on d3 
- [ ] don't forget to update the eventdrops github
