### ISSUE TITLE
As a <User>, I want to <get overlays from N sources>, so that <I can analyze different overlays>

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#786]
* [x] @idanbarak @carmelorr define the configuration limit's (And, Or, Time, Sensor Type)
* [x] @idanbarak @carmelorr define the provider behavior (one fails other success?, one timeout other success?, etc.)
* [x] Design a provider of providers (gets N providers via injection and handles them)
* [x] Implement a provider of providers (gets N "Idahoo" providers (try different tokens) via injection and handle them via configuration)

**Comment by AmitMY** [comment]
Config:
Per provider:
- GeoJSON (Multi Polygon) (or null)
- Time Range (start, end, may be null)
- Sensor Type array

**Comment by idanbarak** [comment]
@AmitMY 
Regarding _"Sensor Type array"_ - i think you should change it "Sensor Name Array".

Please check with @asafMasa and @eldadcohen1

**Comment by carmelorr** [comment]
Please see bug- #898
